/* Python Trainer — course content (en / de / fa) */

const UNITS=[

/* ================= 1 · BASICS ================= */
{ic:'🐍',col:'#306698',lv:'START',
 title:{en:'Python Basics',de:'Python-Grundlagen',fa:'مبانی پایتون'},
 desc:{en:'Variables, numbers, strings & print',de:'Variablen, Zahlen, Strings & print',fa:'متغیرها، اعداد، رشته‌ها و print'},
 blocks:[
  {note:{en:'<b>Variables</b> store values. You create one simply by assigning with <code>=</code>. Python figures out the type by itself — <code>int</code>, <code>float</code>, <code>str</code> or <code>bool</code>.',
         de:'<b>Variablen</b> speichern Werte. Du erzeugst sie einfach mit <code>=</code>. Python erkennt den Typ selbst — <code>int</code>, <code>float</code>, <code>str</code> oder <code>bool</code>.',
         fa:'<b>متغیرها</b> مقدارها را نگه می‌دارند. فقط با <code>=</code> ساخته می‌شوند. پایتون نوع را خودش تشخیص می‌دهد — <code>int</code>، <code>float</code>، <code>str</code> یا <code>bool</code>.'}},
  {code:'age = 34            # int\nprice = 9.99        # float\nname = "Ada"        # str\nhappy = True        # bool\n\nprint(name, "is", age)\nprint(type(price))',label:'variables.py'},
  {note:{en:'<b>Numbers & math.</b> Python is a great calculator: <code>+ - * /</code>, integer division <code>//</code>, remainder <code>%</code> and power <code>**</code>.',
         de:'<b>Zahlen & Mathe.</b> Python ist ein toller Taschenrechner: <code>+ - * /</code>, Ganzzahldivision <code>//</code>, Rest <code>%</code> und Potenz <code>**</code>.',
         fa:'<b>اعداد و ریاضی.</b> پایتون ماشین‌حساب خوبی است: <code>+ - * /</code>، تقسیم صحیح <code>//</code>، باقیمانده <code>%</code> و توان <code>**</code>.'}},
  {code:'print(7 + 3, 7 - 3, 7 * 3)\nprint(7 / 2)     # 3.5  (always float)\nprint(7 // 2)    # 3    (floor division)\nprint(7 % 2)     # 1    (remainder)\nprint(2 ** 10)   # 1024 (power)',label:'math.py'},
  {note:{en:'<b>Strings</b> hold text. Use <b>f-strings</b> to mix values into text: put an <code>f</code> before the quote and write variables in <code>{}</code>.',
         de:'<b>Strings</b> enthalten Text. Mit <b>f-Strings</b> mischst du Werte in Text: ein <code>f</code> vor dem Anführungszeichen, Variablen in <code>{}</code>.',
         fa:'<b>رشته‌ها</b> متن نگه می‌دارند. با <b>f-string</b> مقدارها را داخل متن بگذار: یک <code>f</code> قبل از نقل‌قول و متغیرها داخل <code>{}</code>.'}},
  {code:'name = "Ada"\nlang = "Python"\nyears = 3\n\nprint(f"{name} has used {lang} for {years} years")\nprint(f"Next year: {years + 1}")\nprint(name.upper(), len(name))',label:'strings.py'},
  {note:{en:'Try changing the numbers and text above, then press <b>▶ Run</b> again — this is a real Python running on your device!',
         de:'Ändere oben Zahlen und Text und drücke wieder <b>▶ Run</b> — das ist echtes Python auf deinem Gerät!',
         fa:'اعداد و متن بالا را عوض کن و دوباره <b>▶ Run</b> بزن — این پایتون واقعی روی دستگاه توست!'}},
 ],
 quiz:[
  {q:{en:'What does this print?',de:'Was gibt das aus?',fa:'خروجی چیست؟'},code:'x = 7\ny = 2\nprint(x // y)',
   opts:['3.5','3','4','7.2'],a:1,
   ex:{en:'<code>//</code> is floor division: 7 // 2 = 3.',de:'<code>//</code> ist Ganzzahldivision: 7 // 2 = 3.',fa:'<code>//</code> تقسیم صحیح است: 7 // 2 = 3.'}},
  {q:{en:'Which type does <code>3.0</code> have?',de:'Welchen Typ hat <code>3.0</code>?',fa:'نوع <code>3.0</code> چیست؟'},
   opts:['int','float','str','bool'],a:1,
   ex:{en:'A decimal point makes it a float.',de:'Der Dezimalpunkt macht es zu float.',fa:'نقطه اعشار آن را float می‌کند.'}},
  {q:{en:'What does this print?',de:'Was gibt das aus?',fa:'خروجی چیست؟'},code:'name = "Py"\nprint(f"Hi {name}{name}!")',
   opts:['Hi PyPy!','Hi Py Py!','Hi {name}{name}!','Error'],a:0,
   ex:{en:'f-strings replace each {name} with its value.',de:'f-Strings ersetzen jedes {name} durch den Wert.',fa:'f-string هر {name} را با مقدارش جایگزین می‌کند.'}},
  {q:{en:'What is <code>2 ** 3</code>?',de:'Was ist <code>2 ** 3</code>?',fa:'حاصل <code>2 ** 3</code> چیست؟'},
   opts:['6','8','9','23'],a:1,
   ex:{en:'<code>**</code> is the power operator: 2·2·2 = 8.',de:'<code>**</code> ist Potenz: 2·2·2 = 8.',fa:'<code>**</code> عملگر توان است: ۲×۲×۲=۸.'}},
  {q:{en:'What does <code>len("hello")</code> return?',de:'Was liefert <code>len("hello")</code>?',fa:'<code>len("hello")</code> چه برمی‌گرداند؟'},
   opts:['4','5','6','"hello"'],a:1,
   ex:{en:'len() counts the characters — h e l l o = 5.',de:'len() zählt die Zeichen — h e l l o = 5.',fa:'len() تعداد حروف را می‌شمارد — ۵ حرف.'}},
  {q:{en:'What does this print?',de:'Was gibt das aus?',fa:'خروجی چیست؟'},code:'print(10 % 3)',
   opts:['3','1','0','3.33'],a:1,
   ex:{en:'<code>%</code> gives the remainder: 10 = 3·3 + 1.',de:'<code>%</code> gibt den Rest: 10 = 3·3 + 1.',fa:'<code>%</code> باقیمانده است: ۱۰ = ۳×۳ + ۱.'}},
 ]},

/* ================= 2 · COLLECTIONS ================= */
{ic:'🧺',col:'#2b8a78',lv:'BASICS',
 title:{en:'Lists & Dicts',de:'Listen & Dicts',fa:'لیست‌ها و دیکشنری‌ها'},
 desc:{en:'Lists, slicing, dicts, tuples & sets',de:'Listen, Slicing, Dicts, Tupel & Sets',fa:'لیست، برش، دیکشنری، تاپل و مجموعه'},
 blocks:[
  {note:{en:'A <b>list</b> is an ordered collection. Index from 0, use negative indexes from the end, and <b>slice</b> with <code>[start:stop]</code> (stop is excluded).',
         de:'Eine <b>Liste</b> ist eine geordnete Sammlung. Index ab 0, negative Indizes zählen vom Ende, <b>Slicing</b> mit <code>[start:stop]</code> (stop ist exklusiv).',
         fa:'<b>لیست</b> مجموعه‌ای مرتب است. اندیس از ۰ شروع می‌شود، اندیس منفی از انتها می‌شمارد و <b>برش</b> با <code>[start:stop]</code> است (stop شامل نمی‌شود).'}},
  {code:'fruits = ["apple", "banana", "cherry", "date"]\n\nprint(fruits[0])      # first\nprint(fruits[-1])     # last\nprint(fruits[1:3])    # slice\n\nfruits.append("fig")\nprint(len(fruits), fruits)',label:'lists.py'},
  {note:{en:'A <b>dict</b> maps keys to values — perfect for structured data. A <b>tuple</b> is like a list but immutable; a <b>set</b> keeps only unique values.',
         de:'Ein <b>Dict</b> bildet Schlüssel auf Werte ab — perfekt für strukturierte Daten. Ein <b>Tupel</b> ist wie eine Liste, aber unveränderlich; ein <b>Set</b> enthält nur eindeutige Werte.',
         fa:'<b>دیکشنری</b> کلید را به مقدار وصل می‌کند — عالی برای داده ساخت‌یافته. <b>تاپل</b> مثل لیست ولی تغییرناپذیر است؛ <b>مجموعه</b> فقط مقادیر یکتا دارد.'}},
  {code:'person = {"name": "Ada", "age": 36}\nprint(person["name"])\nperson["city"] = "London"\nprint(person)\n\npoint = (3, 4)          # tuple\nnums = {1, 2, 2, 3, 3}  # set\nprint(point[0], nums)',label:'dicts.py'},
  {code:'squares = [1, 4, 9, 16, 25, 36]\nprint(squares[::2])    # every 2nd\nprint(squares[::-1])   # reversed\nprint(9 in squares)    # membership\nprint(sum(squares), max(squares))',label:'slicing.py'},
 ],
 quiz:[
  {q:{en:'What does this print?',de:'Was gibt das aus?',fa:'خروجی چیست؟'},code:'a = [10, 20, 30, 40]\nprint(a[-1])',
   opts:['10','40','30','Error'],a:1,
   ex:{en:'Index -1 is the last element.',de:'Index -1 ist das letzte Element.',fa:'اندیس ۱- آخرین عنصر است.'}},
  {q:{en:'What does <code>[1,2,3,4][1:3]</code> give?',de:'Was ergibt <code>[1,2,3,4][1:3]</code>?',fa:'<code>[1,2,3,4][1:3]</code> چه می‌دهد؟'},
   opts:['[1, 2, 3]','[2, 3]','[2, 3, 4]','[1, 2]'],a:1,
   ex:{en:'Slices include start, exclude stop: indexes 1 and 2.',de:'Slices: start inklusiv, stop exklusiv — Index 1 und 2.',fa:'برش start را شامل و stop را حذف می‌کند: اندیس ۱ و ۲.'}},
  {q:{en:'How do you read the value of key <code>"age"</code>?',de:'Wie liest man den Wert des Schlüssels <code>"age"</code>?',fa:'مقدار کلید <code>"age"</code> را چگونه می‌خوانی؟'},code:'d = {"name": "Ada", "age": 36}',
   opts:['d.age','d["age"]','d(age)','d{age}'],a:1,
   ex:{en:'Dict values are read with square brackets: d["age"].',de:'Dict-Werte liest man mit eckigen Klammern: d["age"].',fa:'مقدار دیکشنری با کروشه خوانده می‌شود: d["age"].'}},
  {q:{en:'What does this print?',de:'Was gibt das aus?',fa:'خروجی چیست؟'},code:'s = {1, 2, 2, 3, 3, 3}\nprint(len(s))',
   opts:['6','3','1','Error'],a:1,
   ex:{en:'Sets keep only unique values: {1, 2, 3}.',de:'Sets behalten nur eindeutige Werte: {1, 2, 3}.',fa:'مجموعه فقط مقادیر یکتا را نگه می‌دارد: {1,2,3}.'}},
  {q:{en:'Which one CANNOT be changed after creation?',de:'Was kann nach dem Erstellen NICHT geändert werden?',fa:'کدام‌یک بعد از ساخت قابل تغییر نیست؟'},
   opts:['list','dict','tuple','set'],a:2,
   ex:{en:'Tuples are immutable.',de:'Tupel sind unveränderlich.',fa:'تاپل تغییرناپذیر است.'}},
  {q:{en:'What does <code>[1,2,3][::-1]</code> give?',de:'Was ergibt <code>[1,2,3][::-1]</code>?',fa:'<code>[1,2,3][::-1]</code> چه می‌دهد؟'},
   opts:['[1, 2, 3]','[3, 2, 1]','[1, 3]','Error'],a:1,
   ex:{en:'Step -1 walks the list backwards.',de:'Schritt -1 läuft rückwärts durch die Liste.',fa:'گام ۱- لیست را برعکس می‌کند.'}},
 ]},

/* ================= 3 · CONTROL FLOW ================= */
{ic:'🔀',col:'#b06325',lv:'BASICS',
 title:{en:'Control Flow',de:'Kontrollfluss',fa:'کنترل جریان'},
 desc:{en:'if / elif / else, for & while loops',de:'if / elif / else, for- & while-Schleifen',fa:'شرط‌ها و حلقه‌های for و while'},
 blocks:[
  {note:{en:'<b>if / elif / else</b> chooses a branch. Indentation (4 spaces) defines the block — no braces in Python!',
         de:'<b>if / elif / else</b> wählt einen Zweig. Die Einrückung (4 Leerzeichen) definiert den Block — keine Klammern in Python!',
         fa:'<b>if / elif / else</b> مسیر را انتخاب می‌کند. تورفتگی (۴ فاصله) بلوک را مشخص می‌کند — در پایتون آکولاد نداریم!'}},
  {code:'temp = 23\n\nif temp > 30:\n    print("hot 🥵")\nelif temp > 15:\n    print("nice 🙂")\nelse:\n    print("cold 🥶")',label:'if.py'},
  {note:{en:'<b>for</b> iterates over anything: lists, strings, or <code>range(n)</code> (0 … n-1). <code>enumerate</code> also gives you the index.',
         de:'<b>for</b> iteriert über alles: Listen, Strings oder <code>range(n)</code> (0 … n-1). <code>enumerate</code> liefert zusätzlich den Index.',
         fa:'<b>for</b> روی همه‌چیز می‌چرخد: لیست، رشته یا <code>range(n)</code> (از ۰ تا n-1). <code>enumerate</code> اندیس را هم می‌دهد.'}},
  {code:'for i in range(5):\n    print(i, i * i)\n\nfor idx, fruit in enumerate(["apple", "banana"]):\n    print(idx, fruit)',label:'for.py'},
  {note:{en:'<b>while</b> repeats as long as a condition is true. <code>break</code> exits the loop, <code>continue</code> skips to the next round.',
         de:'<b>while</b> wiederholt, solange eine Bedingung wahr ist. <code>break</code> verlässt die Schleife, <code>continue</code> springt zur nächsten Runde.',
         fa:'<b>while</b> تا وقتی شرط برقرار است تکرار می‌کند. <code>break</code> از حلقه خارج می‌شود و <code>continue</code> به دور بعد می‌رود.'}},
  {code:'n = 1\nwhile n < 100:\n    n = n * 2\n    if n == 32:\n        continue     # skip printing 32\n    print(n)\nprint("done, n =", n)',label:'while.py'},
 ],
 quiz:[
  {q:{en:'How many numbers does <code>range(4)</code> produce?',de:'Wie viele Zahlen erzeugt <code>range(4)</code>?',fa:'<code>range(4)</code> چند عدد تولید می‌کند؟'},
   opts:['3','4','5','1'],a:1,
   ex:{en:'range(4) → 0, 1, 2, 3 — four numbers.',de:'range(4) → 0, 1, 2, 3 — vier Zahlen.',fa:'range(4) یعنی ۰،۱،۲،۳ — چهار عدد.'}},
  {q:{en:'What does this print?',de:'Was gibt das aus?',fa:'خروجی چیست؟'},code:'x = 5\nif x > 10:\n    print("big")\nelif x > 3:\n    print("medium")\nelse:\n    print("small")',
   opts:['big','medium','small','nothing'],a:1,
   ex:{en:'5 is not > 10 but is > 3 → "medium".',de:'5 ist nicht > 10, aber > 3 → "medium".',fa:'۵ بزرگ‌تر از ۱۰ نیست ولی از ۳ هست → medium.'}},
  {q:{en:'What ends a loop immediately?',de:'Was beendet eine Schleife sofort?',fa:'چه چیزی حلقه را فوراً تمام می‌کند؟'},
   opts:['continue','pass','break','stop'],a:2,
   ex:{en:'<code>break</code> exits the loop at once.',de:'<code>break</code> verlässt die Schleife sofort.',fa:'<code>break</code> بلافاصله از حلقه خارج می‌شود.'}},
  {q:{en:'What does this print?',de:'Was gibt das aus?',fa:'خروجی چیست؟'},code:'total = 0\nfor i in range(1, 4):\n    total += i\nprint(total)',
   opts:['6','10','3','7'],a:0,
   ex:{en:'1 + 2 + 3 = 6 (range stops before 4).',de:'1 + 2 + 3 = 6 (range stoppt vor 4).',fa:'۱+۲+۳=۶ (پیش از ۴ متوقف می‌شود).'}},
  {q:{en:'Python marks code blocks with…',de:'Python markiert Codeblöcke mit …',fa:'پایتون بلوک کد را با چه مشخص می‌کند؟'},
   opts:['{ } braces','( ) parentheses','indentation','semicolons'],a:2,
   ex:{en:'Indentation is syntax in Python.',de:'Einrückung ist in Python Syntax.',fa:'تورفتگی در پایتون بخشی از دستور زبان است.'}},
  {q:{en:'What does <code>continue</code> do in a loop?',de:'Was macht <code>continue</code> in einer Schleife?',fa:'<code>continue</code> در حلقه چه می‌کند؟'},
   opts:['ends the loop','skips to the next iteration','restarts the program','pauses'],a:1,
   ex:{en:'It jumps straight to the next iteration.',de:'Es springt direkt zur nächsten Iteration.',fa:'مستقیم به تکرار بعدی می‌پرد.'}},
 ]},

/* ================= 4 · FUNCTIONS ================= */
{ic:'🧩',col:'#7b5fe0',lv:'BASICS',
 title:{en:'Functions',de:'Funktionen',fa:'توابع'},
 desc:{en:'def, return, lambda & comprehensions',de:'def, return, lambda & Comprehensions',fa:'def، return، lambda و comprehension'},
 blocks:[
  {note:{en:'<b>Functions</b> package code you want to reuse. Define with <code>def</code>, give back a result with <code>return</code>. Parameters can have <b>default values</b>.',
         de:'<b>Funktionen</b> verpacken wiederverwendbaren Code. Definiert mit <code>def</code>, Ergebnis mit <code>return</code>. Parameter können <b>Standardwerte</b> haben.',
         fa:'<b>تابع</b> کدی است که می‌خواهی دوباره استفاده کنی. با <code>def</code> تعریف و با <code>return</code> نتیجه برگردان. پارامترها می‌توانند <b>مقدار پیش‌فرض</b> داشته باشند.'}},
  {code:'def greet(name, lang="en"):\n    if lang == "de":\n        return f"Hallo {name}!"\n    return f"Hello {name}!"\n\nprint(greet("Ada"))\nprint(greet("Ada", lang="de"))',label:'functions.py'},
  {note:{en:'A <b>list comprehension</b> builds a list in one line: <code>[expr for x in seq if cond]</code>. A <b>lambda</b> is a tiny anonymous function.',
         de:'Eine <b>List Comprehension</b> baut eine Liste in einer Zeile: <code>[ausdruck for x in seq if bedingung]</code>. Ein <b>Lambda</b> ist eine winzige anonyme Funktion.',
         fa:'<b>List comprehension</b> لیست را در یک خط می‌سازد: <code>[expr for x in seq if cond]</code>. <b>lambda</b> تابع کوچک بی‌نام است.'}},
  {code:'squares = [x * x for x in range(8)]\nevens = [x for x in range(20) if x % 2 == 0]\nprint(squares)\nprint(evens)\n\ndouble = lambda x: 2 * x\nprint(double(21))\nprint(sorted(["banana","fig","apple"], key=len))',label:'comprehensions.py'},
  {note:{en:'<b>Modules</b> extend Python: <code>import math</code> gives you π, square roots and more. This is exactly how NumPy & friends work too.',
         de:'<b>Module</b> erweitern Python: <code>import math</code> liefert π, Wurzeln und mehr. Genau so funktionieren auch NumPy & Co.',
         fa:'<b>ماژول‌ها</b> پایتون را گسترش می‌دهند: <code>import math</code> عدد π، جذر و بیشتر می‌دهد. NumPy و بقیه هم همین‌طورند.'}},
  {code:'import math\n\nprint(math.pi)\nprint(math.sqrt(2))\nprint(math.floor(3.7), math.ceil(3.2))\nprint(round(math.e, 3))',label:'modules.py'},
 ],
 quiz:[
  {q:{en:'What does this print?',de:'Was gibt das aus?',fa:'خروجی چیست؟'},code:'def f(x, y=10):\n    return x + y\n\nprint(f(5))',
   opts:['5','15','10','Error'],a:1,
   ex:{en:'y falls back to its default 10 → 5 + 10.',de:'y nimmt den Standardwert 10 → 5 + 10.',fa:'y مقدار پیش‌فرض ۱۰ را می‌گیرد → ۵+۱۰.'}},
  {q:{en:'What does a function without <code>return</code> give back?',de:'Was liefert eine Funktion ohne <code>return</code>?',fa:'تابع بدون <code>return</code> چه برمی‌گرداند؟'},
   opts:['0','""','None','Error'],a:2,
   ex:{en:'No return → the function returns None.',de:'Ohne return → die Funktion liefert None.',fa:'بدون return مقدار None برمی‌گردد.'}},
  {q:{en:'What is <code>[x*x for x in range(4)]</code>?',de:'Was ist <code>[x*x for x in range(4)]</code>?',fa:'<code>[x*x for x in range(4)]</code> چیست؟'},
   opts:['[0, 1, 4, 9]','[1, 4, 9, 16]','[0, 1, 2, 3]','[1, 2, 3, 4]'],a:0,
   ex:{en:'Squares of 0..3: 0, 1, 4, 9.',de:'Quadrate von 0..3: 0, 1, 4, 9.',fa:'مربع ۰ تا ۳: ۰،۱،۴،۹.'}},
  {q:{en:'Which line defines a lambda that adds 1?',de:'Welche Zeile definiert ein Lambda, das 1 addiert?',fa:'کدام خط lambda برای افزودن ۱ است؟'},
   opts:['lambda x: x + 1','def x: x + 1','lambda(x) = x + 1','x => x + 1'],a:0,
   ex:{en:'lambda parameters: expression.',de:'lambda Parameter: Ausdruck.',fa:'ساختار: lambda ورودی: عبارت.'}},
  {q:{en:'What does this print?',de:'Was gibt das aus?',fa:'خروجی چیست؟'},code:'nums = [3, 1, 2]\nprint(sorted(nums), nums[0])',
   opts:['[1, 2, 3] 3','[1, 2, 3] 1','[3, 1, 2] 3','Error'],a:0,
   ex:{en:'sorted() returns a NEW list; nums is unchanged.',de:'sorted() liefert eine NEUE Liste; nums bleibt gleich.',fa:'sorted() لیست جدید می‌دهد؛ nums تغییر نمی‌کند.'}},
  {q:{en:'How do you import the math module?',de:'Wie importiert man das math-Modul?',fa:'ماژول math را چگونه وارد می‌کنی؟'},
   opts:['include math','import math','using math','load math'],a:1,
   ex:{en:'<code>import math</code> — then use math.pi etc.',de:'<code>import math</code> — dann math.pi usw.',fa:'<code>import math</code> — سپس math.pi و غیره.'}},
 ]},

/* ================= 5 · NUMPY I ================= */
{ic:'🔢',col:'#4b8bbe',lv:'NUMPY',
 title:{en:'NumPy Arrays',de:'NumPy-Arrays',fa:'آرایه‌های NumPy'},
 desc:{en:'Arrays, arange, slicing & masks',de:'Arrays, arange, Slicing & Masken',fa:'آرایه، arange، برش و ماسک'},
 blocks:[
  {note:{en:'<b>NumPy</b> is THE library for numeric computing. Its <code>ndarray</code> holds numbers of one type and computes <b>element-wise</b> — no loops needed!',
         de:'<b>NumPy</b> ist DIE Bibliothek fürs numerische Rechnen. Das <code>ndarray</code> enthält Zahlen eines Typs und rechnet <b>elementweise</b> — ganz ohne Schleifen!',
         fa:'<b>NumPy</b> کتابخانه اصلی محاسبات عددی است. <code>ndarray</code> اعداد هم‌نوع را نگه می‌دارد و <b>عنصر به عنصر</b> حساب می‌کند — بدون حلقه!'}},
  {code:'import numpy as np\n\na = np.array([1, 2, 3, 4])\nprint(a * 10)        # element-wise!\nprint(a + a)\nprint(a.dtype, a.shape)',label:'arrays.py'},
  {note:{en:'Create ranges with <code>np.arange(start, stop, step)</code> and evenly spaced points with <code>np.linspace(a, b, n)</code>. Reshape to make matrices.',
         de:'Bereiche mit <code>np.arange(start, stop, step)</code>, gleichmäßige Punkte mit <code>np.linspace(a, b, n)</code>. Mit reshape entstehen Matrizen.',
         fa:'با <code>np.arange</code> بازه بساز و با <code>np.linspace(a,b,n)</code> نقاط با فاصله برابر. با reshape ماتریس بساز.'}},
  {code:'import numpy as np\n\nprint(np.arange(0, 10, 2))\nprint(np.linspace(0, 1, 5))\n\nm = np.arange(12).reshape(3, 4)\nprint(m)\nprint("row 1:", m[1])\nprint("col 2:", m[:, 2])',label:'ranges.py'},
  {note:{en:'<b>Boolean masks</b> are NumPy superpowers: compare an array, get True/False, and use it to filter.',
         de:'<b>Boolesche Masken</b> sind NumPys Superkraft: Array vergleichen, True/False bekommen, damit filtern.',
         fa:'<b>ماسک بولی</b> ابرقدرت NumPy است: آرایه را مقایسه کن، True/False بگیر و با آن فیلتر کن.'}},
  {code:'import numpy as np\n\nx = np.array([3, 8, 1, 9, 5, 7])\nmask = x > 4\nprint(mask)\nprint(x[mask])          # filter\nprint(x[x % 2 == 1])    # odd values only',label:'masks.py'},
 ],
 quiz:[
  {q:{en:'What does this print?',de:'Was gibt das aus?',fa:'خروجی چیست؟'},code:'import numpy as np\na = np.array([1, 2, 3])\nprint(a * 2)',
   opts:['[1 2 3 1 2 3]','[2 4 6]','[1 4 9]','Error'],a:1,
   ex:{en:'NumPy multiplies element-wise (a Python list would repeat!).',de:'NumPy rechnet elementweise (eine Python-Liste würde wiederholen!).',fa:'NumPy عنصر به عنصر ضرب می‌کند (لیست پایتون تکرار می‌شد!).'}},
  {q:{en:'What is <code>np.arange(0, 10, 3)</code>?',de:'Was ist <code>np.arange(0, 10, 3)</code>?',fa:'<code>np.arange(0,10,3)</code> چیست؟'},
   opts:['[0 3 6 9]','[0 3 6 9 12]','[3 6 9]','[0 10 3]'],a:0,
   ex:{en:'Start 0, step 3, stop before 10.',de:'Start 0, Schritt 3, Stopp vor 10.',fa:'از ۰ با گام ۳ تا قبل از ۱۰.'}},
  {q:{en:'How many values does <code>np.linspace(0, 1, 5)</code> return?',de:'Wie viele Werte liefert <code>np.linspace(0, 1, 5)</code>?',fa:'<code>np.linspace(0,1,5)</code> چند مقدار می‌دهد؟'},
   opts:['4','5','6','10'],a:1,
   ex:{en:'linspace(a, b, n) returns exactly n points, ends included.',de:'linspace(a, b, n) liefert genau n Punkte, Enden inklusive.',fa:'linspace دقیقاً n نقطه می‌دهد، هر دو سر شامل.'}},
  {q:{en:'For a 3×4 matrix m, what is <code>m[:, 0]</code>?',de:'Für eine 3×4-Matrix m: was ist <code>m[:, 0]</code>?',fa:'برای ماتریس ۳×۴، <code>m[:,0]</code> چیست؟'},
   opts:['first row','first column','element (0,0)','last column'],a:1,
   ex:{en:'“:” = all rows, 0 = column 0 → the first column.',de:'„:“ = alle Zeilen, 0 = Spalte 0 → die erste Spalte.',fa:'«:» یعنی همه سطرها و ۰ یعنی ستون اول.'}},
  {q:{en:'What does this print?',de:'Was gibt das aus?',fa:'خروجی چیست؟'},code:'import numpy as np\nx = np.array([5, 12, 3, 20])\nprint(x[x > 10])',
   opts:['[12 20]','[5 3]','[True False]','[10 20]'],a:0,
   ex:{en:'The mask keeps values greater than 10.',de:'Die Maske behält Werte über 10.',fa:'ماسک فقط مقادیر بزرگ‌تر از ۱۰ را نگه می‌دارد.'}},
  {q:{en:'What is the shape of <code>np.arange(12).reshape(3, 4)</code>?',de:'Welche Form hat <code>np.arange(12).reshape(3, 4)</code>?',fa:'شکل <code>np.arange(12).reshape(3,4)</code> چیست؟'},
   opts:['(12,)','(4, 3)','(3, 4)','(2, 6)'],a:2,
   ex:{en:'reshape(3, 4) → 3 rows, 4 columns.',de:'reshape(3, 4) → 3 Zeilen, 4 Spalten.',fa:'reshape(3,4) یعنی ۳ سطر و ۴ ستون.'}},
 ]},

/* ================= 6 · NUMPY II & SCIPY ================= */
{ic:'➗',col:'#2b6cb0',lv:'NUMPY',
 title:{en:'NumPy Math & SciPy',de:'NumPy-Mathe & SciPy',fa:'ریاضی NumPy و SciPy'},
 desc:{en:'Statistics, broadcasting, random & SciPy',de:'Statistik, Broadcasting, Zufall & SciPy',fa:'آمار، broadcasting، تصادف و SciPy'},
 blocks:[
  {note:{en:'Arrays know their own <b>statistics</b>: <code>mean, std, min, max, sum</code>. With an <code>axis</code> you aggregate rows or columns of a matrix.',
         de:'Arrays kennen ihre <b>Statistik</b>: <code>mean, std, min, max, sum</code>. Mit <code>axis</code> aggregierst du Zeilen oder Spalten einer Matrix.',
         fa:'آرایه‌ها <b>آمار</b> خودشان را می‌دانند: <code>mean, std, min, max, sum</code>. با <code>axis</code> روی سطر یا ستون ماتریس جمع می‌زنی.'}},
  {code:'import numpy as np\n\ndata = np.array([[4, 9, 2],\n                 [7, 1, 6]])\nprint("mean:", data.mean())\nprint("per column:", data.mean(axis=0))\nprint("per row:   ", data.sum(axis=1))\nprint("max:", data.max(), "std:", round(data.std(), 2))',label:'stats.py'},
  {note:{en:'<b>Broadcasting</b>: NumPy stretches shapes automatically — combine a matrix with a row or a scalar without writing loops.',
         de:'<b>Broadcasting</b>: NumPy dehnt Formen automatisch — kombiniere Matrix mit Zeile oder Skalar ganz ohne Schleifen.',
         fa:'<b>Broadcasting</b>: NumPy شکل‌ها را خودکار هماهنگ می‌کند — ماتریس را با سطر یا عدد ترکیب کن، بدون حلقه.'}},
  {code:'import numpy as np\n\nm = np.zeros((3, 3)) + np.array([1, 2, 3])\nprint(m)\n\nrng = np.random.default_rng(42)\nr = rng.integers(1, 7, size=10)   # dice rolls\nprint(r, "mean:", r.mean())',label:'broadcast.py'},
  {note:{en:'<b>SciPy</b> builds on NumPy: <code>scipy.stats</code> for statistics, <code>scipy.integrate</code> for integrals, <code>scipy.optimize</code> to find minima and roots.',
         de:'<b>SciPy</b> baut auf NumPy auf: <code>scipy.stats</code> für Statistik, <code>scipy.integrate</code> für Integrale, <code>scipy.optimize</code> für Minima und Nullstellen.',
         fa:'<b>SciPy</b> روی NumPy ساخته شده: <code>scipy.stats</code> برای آمار، <code>scipy.integrate</code> برای انتگرال و <code>scipy.optimize</code> برای کمینه و ریشه.'}},
  {code:'from scipy import integrate, optimize\nimport numpy as np\n\n# integral of sin(x) from 0 to pi  (= 2)\narea, err = integrate.quad(np.sin, 0, np.pi)\nprint("area:", round(area, 6))\n\n# minimum of (x-3)^2 + 1\nres = optimize.minimize_scalar(lambda x: (x - 3)**2 + 1)\nprint("minimum at x =", round(res.x, 3))',label:'scipy_intro.py'},
  {code:'from scipy import stats\nimport numpy as np\n\nheights = np.array([170, 165, 180, 175, 168, 172, 177])\nprint("mean:", np.mean(heights))\nprint("median:", np.median(heights))\nz = stats.zscore(heights)\nprint("z-scores:", np.round(z, 2))',label:'scipy_stats.py'},
 ],
 quiz:[
  {q:{en:'What does <code>np.array([[1,2],[3,4]]).mean()</code> give?',de:'Was ergibt <code>np.array([[1,2],[3,4]]).mean()</code>?',fa:'<code>mean()</code> برای [[1,2],[3,4]] چیست؟'},
   opts:['2.5','10','2','[2, 3]'],a:0,
   ex:{en:'(1+2+3+4)/4 = 2.5.',de:'(1+2+3+4)/4 = 2,5.',fa:'(۱+۲+۳+۴)/۴ = ۲٫۵.'}},
  {q:{en:'<code>data.mean(axis=0)</code> averages over…',de:'<code>data.mean(axis=0)</code> mittelt über …',fa:'<code>mean(axis=0)</code> روی چه میانگین می‌گیرد؟'},
   opts:['each row','each column','the whole array','nothing'],a:1,
   ex:{en:'axis=0 collapses the rows → one value per column.',de:'axis=0 kollabiert die Zeilen → ein Wert pro Spalte.',fa:'axis=0 سطرها را جمع می‌کند → یک مقدار برای هر ستون.'}},
  {q:{en:'What shape results from <code>np.zeros((2,3)) + np.array([1,2,3])</code>?',de:'Welche Form hat <code>np.zeros((2,3)) + np.array([1,2,3])</code>?',fa:'شکل حاصل <code>zeros((2,3)) + [1,2,3]</code> چیست؟'},
   opts:['(2, 3)','(3, 2)','(6,)','Error'],a:0,
   ex:{en:'The row [1,2,3] is broadcast onto both rows → (2,3).',de:'Die Zeile [1,2,3] wird auf beide Zeilen gebroadcastet → (2,3).',fa:'سطر [1,2,3] روی هر دو سطر پخش می‌شود → (2,3).'}},
  {q:{en:'Which SciPy module computes integrals?',de:'Welches SciPy-Modul berechnet Integrale?',fa:'کدام ماژول SciPy انتگرال می‌گیرد؟'},
   opts:['scipy.stats','scipy.integrate','scipy.optimize','scipy.linalg'],a:1,
   ex:{en:'scipy.integrate — e.g. quad() for 1-D integrals.',de:'scipy.integrate — z. B. quad() für 1-D-Integrale.',fa:'scipy.integrate — مثلاً quad برای انتگرال یک‌بعدی.'}},
  {q:{en:'<code>integrate.quad(np.sin, 0, np.pi)</code> ≈ ?',de:'<code>integrate.quad(np.sin, 0, np.pi)</code> ≈ ?',fa:'<code>quad(np.sin,0,π)</code> تقریباً چند است؟'},
   opts:['0','1','2','3.14'],a:2,
   ex:{en:'∫ sin(x) dx from 0 to π = 2.',de:'∫ sin(x) dx von 0 bis π = 2.',fa:'انتگرال sin از ۰ تا π برابر ۲ است.'}},
  {q:{en:'Why seed a generator: <code>default_rng(42)</code>?',de:'Warum einen Generator seeden: <code>default_rng(42)</code>?',fa:'چرا <code>default_rng(42)</code> را seed می‌کنیم؟'},
   opts:['faster random numbers','reproducible results','bigger numbers','it is required'],a:1,
   ex:{en:'Same seed → same “random” sequence every run.',de:'Gleicher Seed → gleiche „Zufalls“-Folge bei jedem Lauf.',fa:'seed یکسان → همان دنباله تصادفی در هر اجرا.'}},
 ]},

/* ================= 7 · PANDAS ================= */
{ic:'🐼',col:'#5a4bc0',lv:'DATA',
 title:{en:'Pandas',de:'Pandas',fa:'پانداس'},
 desc:{en:'DataFrames, selection, filtering, groupby',de:'DataFrames, Auswahl, Filter, groupby',fa:'دیتافریم، انتخاب، فیلتر و groupby'},
 blocks:[
  {note:{en:'<b>Pandas</b> is Python\'s spreadsheet. A <b>DataFrame</b> is a table with named columns; a <b>Series</b> is one column.',
         de:'<b>Pandas</b> ist Pythons Tabellenkalkulation. Ein <b>DataFrame</b> ist eine Tabelle mit benannten Spalten; eine <b>Series</b> ist eine Spalte.',
         fa:'<b>پانداس</b> صفحه‌گسترده پایتون است. <b>DataFrame</b> جدولی با ستون‌های نام‌دار و <b>Series</b> یک ستون است.'}},
  {code:'import pandas as pd\n\ndf = pd.DataFrame({\n    "city": ["Berlin", "Munich", "Hamburg", "Cologne"],\n    "pop":  [3.7, 1.5, 1.9, 1.1],      # millions\n    "area": [892, 310, 755, 405],      # km2\n})\nprint(df)\nprint()\nprint(df.describe().round(2))',label:'dataframe.py'},
  {note:{en:'Select a column with <code>df["col"]</code>, rows by position with <code>df.iloc[i]</code>, and filter with a boolean condition — just like NumPy masks.',
         de:'Spalte mit <code>df["col"]</code> wählen, Zeilen per Position mit <code>df.iloc[i]</code>, filtern mit boolescher Bedingung — wie NumPy-Masken.',
         fa:'ستون را با <code>df["col"]</code>، سطر را با <code>df.iloc[i]</code> بگیر و با شرط بولی فیلتر کن — مثل ماسک NumPy.'}},
  {code:'import pandas as pd\ndf = pd.DataFrame({\n    "city": ["Berlin", "Munich", "Hamburg", "Cologne"],\n    "pop":  [3.7, 1.5, 1.9, 1.1],\n})\n\nprint(df["pop"].mean())          # column stats\nprint(df.iloc[0])                # first row\nbig = df[df["pop"] > 1.4]        # filter!\nprint(big)',label:'select.py'},
  {note:{en:'New columns come from calculations on existing ones. <b>groupby</b> splits data into groups and aggregates each — the heart of data analysis.',
         de:'Neue Spalten entstehen aus Berechnungen. <b>groupby</b> teilt Daten in Gruppen und aggregiert sie — das Herz der Datenanalyse.',
         fa:'ستون جدید از محاسبه روی ستون‌های موجود ساخته می‌شود. <b>groupby</b> داده را گروه‌بندی و خلاصه می‌کند — قلب تحلیل داده.'}},
  {code:'import pandas as pd\n\nsales = pd.DataFrame({\n    "fruit": ["apple","apple","banana","banana","cherry"],\n    "qty":   [3, 5, 2, 7, 4],\n    "price": [1.2, 1.1, 0.5, 0.4, 2.5],\n})\nsales["total"] = sales.qty * sales.price\nprint(sales)\nprint()\nprint(sales.groupby("fruit")["total"].sum())',label:'groupby.py'},
 ],
 quiz:[
  {q:{en:'How do you select the column <code>"pop"</code>?',de:'Wie wählt man die Spalte <code>"pop"</code>?',fa:'ستون <code>"pop"</code> را چگونه انتخاب می‌کنی؟'},
   opts:['df.get.pop','df["pop"]','df(pop)','df{"pop"}'],a:1,
   ex:{en:'Square brackets with the column name (df.pop would clash with a method).',de:'Eckige Klammern mit Spaltennamen.',fa:'کروشه با نام ستون.'}},
  {q:{en:'What does <code>df.iloc[0]</code> return?',de:'Was liefert <code>df.iloc[0]</code>?',fa:'<code>df.iloc[0]</code> چه می‌دهد؟'},
   opts:['first column','first row','cell (0,0)','the index'],a:1,
   ex:{en:'iloc selects by position — row 0.',de:'iloc wählt nach Position — Zeile 0.',fa:'iloc بر اساس موقعیت انتخاب می‌کند — سطر ۰.'}},
  {q:{en:'What does <code>df[df["pop"] > 2]</code> do?',de:'Was macht <code>df[df["pop"] > 2]</code>?',fa:'<code>df[df["pop"]>2]</code> چه می‌کند؟'},
   opts:['sorts by pop','keeps rows where pop > 2','deletes the pop column','sets pop to 2'],a:1,
   ex:{en:'Boolean filtering keeps matching rows.',de:'Boolesches Filtern behält passende Zeilen.',fa:'فیلتر بولی فقط سطرهای درست را نگه می‌دارد.'}},
  {q:{en:'Which method shows count / mean / std per column?',de:'Welche Methode zeigt count / mean / std pro Spalte?',fa:'کدام متد count/mean/std هر ستون را می‌دهد؟'},
   opts:['df.info()','df.describe()','df.head()','df.stats()'],a:1,
   ex:{en:'describe() summarises the numeric columns.',de:'describe() fasst numerische Spalten zusammen.',fa:'describe() خلاصه آماری ستون‌های عددی است.'}},
  {q:{en:'What does this print?',de:'Was gibt das aus?',fa:'خروجی چیست؟'},code:'import pandas as pd\ns = pd.Series([2, 4, 6])\nprint(s.mean())',
   opts:['4.0','12','6','2'],a:0,
   ex:{en:'(2+4+6)/3 = 4.0.',de:'(2+4+6)/3 = 4,0.',fa:'(۲+۴+۶)/۳ = ۴.'}},
  {q:{en:'<code>sales.groupby("fruit")["qty"].sum()</code> gives…',de:'<code>sales.groupby("fruit")["qty"].sum()</code> liefert …',fa:'<code>groupby("fruit")["qty"].sum()</code> چه می‌دهد؟'},
   opts:['total qty per fruit','the biggest fruit','qty of the first fruit','a sorted table'],a:0,
   ex:{en:'groupby splits per fruit, sum() adds each group\'s qty.',de:'groupby teilt pro Frucht, sum() addiert je Gruppe.',fa:'groupby بر اساس میوه جدا می‌کند و sum جمع هر گروه است.'}},
 ]},

/* ================= 8 · MATPLOTLIB ================= */
{ic:'📊',col:'#c0356b',lv:'PLOTS',
 title:{en:'Matplotlib',de:'Matplotlib',fa:'مت‌پلات‌لیب'},
 desc:{en:'Line, scatter, bar & histogram plots',de:'Linien-, Streu-, Balken- & Histogramm-Plots',fa:'نمودار خطی، پراکندگی، میله‌ای و هیستوگرام'},
 blocks:[
  {note:{en:'<b>Matplotlib</b> draws charts. The pattern is always: prepare data → <code>plt.plot(...)</code> → labels → <code>plt.show()</code>. Run the examples — the figure appears right below!',
         de:'<b>Matplotlib</b> zeichnet Diagramme. Das Muster: Daten vorbereiten → <code>plt.plot(...)</code> → Beschriften → <code>plt.show()</code>. Führ die Beispiele aus — die Grafik erscheint direkt darunter!',
         fa:'<b>مت‌پلات‌لیب</b> نمودار می‌کشد. الگو همیشه: آماده‌سازی داده ← <code>plt.plot</code> ← برچسب‌ها ← <code>plt.show()</code>. اجرا کن — شکل همین پایین ظاهر می‌شود!'}},
  {code:'import numpy as np\nimport matplotlib.pyplot as plt\n\nx = np.linspace(0, 2*np.pi, 200)\nplt.plot(x, np.sin(x), label="sin")\nplt.plot(x, np.cos(x), "--", label="cos")\nplt.title("Sine & Cosine")\nplt.xlabel("x"); plt.ylabel("y")\nplt.legend(); plt.grid(True)\nplt.show()',label:'line.py'},
  {note:{en:'<b>Scatter</b> shows point clouds, <b>bar</b> compares categories, <b>hist</b> shows a distribution.',
         de:'<b>Scatter</b> zeigt Punktwolken, <b>bar</b> vergleicht Kategorien, <b>hist</b> zeigt eine Verteilung.',
         fa:'<b>scatter</b> ابر نقاط، <b>bar</b> مقایسه دسته‌ها و <b>hist</b> توزیع را نشان می‌دهد.'}},
  {code:'import numpy as np\nimport matplotlib.pyplot as plt\n\nrng = np.random.default_rng(1)\nx = rng.normal(size=200)\ny = 0.6*x + rng.normal(scale=0.5, size=200)\n\nplt.scatter(x, y, s=14, alpha=0.7, c=x, cmap="viridis")\nplt.colorbar(label="x value")\nplt.title("Correlated scatter")\nplt.show()',label:'scatter.py'},
  {code:'import matplotlib.pyplot as plt\n\ncities = ["Berlin", "Munich", "Hamburg", "Cologne"]\npop = [3.7, 1.5, 1.9, 1.1]\n\nplt.bar(cities, pop, color=["#4b8bbe","#2bb5a0","#f5b027","#c0356b"])\nplt.ylabel("Population (millions)")\nplt.title("German cities")\nplt.show()',label:'bar.py'},
  {code:'import numpy as np\nimport matplotlib.pyplot as plt\n\nrng = np.random.default_rng(7)\ndata = rng.normal(loc=170, scale=8, size=1000)\n\nplt.hist(data, bins=30, color="#4b8bbe", edgecolor="white")\nplt.title("Heights (simulated)")\nplt.xlabel("cm"); plt.ylabel("count")\nplt.show()',label:'hist.py'},
 ],
 quiz:[
  {q:{en:'Which function draws a line chart?',de:'Welche Funktion zeichnet ein Liniendiagramm?',fa:'کدام تابع نمودار خطی می‌کشد؟'},
   opts:['plt.line()','plt.plot()','plt.draw()','plt.chart()'],a:1,
   ex:{en:'plt.plot(x, y) draws lines.',de:'plt.plot(x, y) zeichnet Linien.',fa:'plt.plot(x,y) خط می‌کشد.'}},
  {q:{en:'Which chart shows a distribution best?',de:'Welches Diagramm zeigt eine Verteilung am besten?',fa:'کدام نمودار توزیع را بهتر نشان می‌دهد؟'},
   opts:['bar','scatter','histogram','pie'],a:2,
   ex:{en:'Histograms bin values and show their frequency.',de:'Histogramme gruppieren Werte und zeigen Häufigkeit.',fa:'هیستوگرام فراوانی مقادیر را نشان می‌دهد.'}},
  {q:{en:'What does <code>plt.legend()</code> need to work?',de:'Was braucht <code>plt.legend()</code>?',fa:'<code>plt.legend()</code> به چه نیاز دارد؟'},
   opts:['a title','label= on the plots','a grid','colors'],a:1,
   ex:{en:'Each plot needs label="…" to appear in the legend.',de:'Jeder Plot braucht label="…" für die Legende.',fa:'هر نمودار باید label داشته باشد تا در legend بیاید.'}},
  {q:{en:'Which call compares categories with rectangles?',de:'Welcher Aufruf vergleicht Kategorien mit Rechtecken?',fa:'کدام دستور دسته‌ها را با مستطیل مقایسه می‌کند؟'},
   opts:['plt.bar()','plt.hist()','plt.scatter()','plt.box()'],a:0,
   ex:{en:'plt.bar(categories, values).',de:'plt.bar(Kategorien, Werte).',fa:'plt.bar(دسته‌ها، مقادیر).'}},
  {q:{en:'What does <code>plt.xlabel("x")</code> do?',de:'Was macht <code>plt.xlabel("x")</code>?',fa:'<code>plt.xlabel("x")</code> چه می‌کند؟'},
   opts:['sets the title','labels the x-axis','plots x','creates a legend'],a:1,
   ex:{en:'It labels the horizontal axis.',de:'Es beschriftet die x-Achse.',fa:'محور افقی را برچسب می‌زند.'}},
  {q:{en:'In <code>plt.hist(data, bins=30)</code>, bins controls…',de:'In <code>plt.hist(data, bins=30)</code> steuert bins …',fa:'در <code>hist(data, bins=30)</code>، bins چیست؟'},
   opts:['the color','the number of bars','the axis length','the font'],a:1,
   ex:{en:'bins = how many intervals the data is split into.',de:'bins = Anzahl der Intervalle.',fa:'bins تعداد بازه‌های تقسیم داده است.'}},
 ]},
];

/* ================= playground quick snippets ================= */
const SNIPPETS=[
 {t:'Hello',code:'print("Hello, Python! 🐍")\nfor i in range(3):\n    print("run", i)'},
 {t:'NumPy',code:'import numpy as np\na = np.arange(10)\nprint(a)\nprint("sum:", a.sum(), "mean:", a.mean())'},
 {t:'Plot',code:'import numpy as np\nimport matplotlib.pyplot as plt\nx = np.linspace(0, 10, 300)\nplt.plot(x, np.sin(x) * np.exp(-x/5))\nplt.title("Damped sine")\nplt.show()'},
 {t:'Pandas',code:'import pandas as pd\ndf = pd.DataFrame({"a":[1,2,3],"b":[10,20,30]})\nprint(df)\nprint(df.describe())'},
 {t:'SciPy',code:'from scipy import optimize\nres = optimize.minimize_scalar(lambda x: (x-2)**2 + 1)\nprint("min at x =", round(res.x, 4))'},
];

/* ================= examples library ================= */
const EXAMPLES=[
 {cat:'Python',icon:'🐍',title:{en:'FizzBuzz',de:'FizzBuzz',fa:'فیزباز'},
  code:'for i in range(1, 21):\n    if i % 15 == 0:   print("FizzBuzz")\n    elif i % 3 == 0:  print("Fizz")\n    elif i % 5 == 0:  print("Buzz")\n    else:             print(i)'},
 {cat:'Python',icon:'🔢',title:{en:'Fibonacci numbers',de:'Fibonacci-Zahlen',fa:'اعداد فیبوناچی'},
  code:'a, b = 0, 1\nfor _ in range(12):\n    print(a, end=" ")\n    a, b = b, a + b\nprint()'},
 {cat:'Python',icon:'🔤',title:{en:'Word frequency counter',de:'Worthäufigkeit zählen',fa:'شمارش تکرار کلمات'},
  code:'text = "the quick brown fox jumps over the lazy dog the fox"\ncounts = {}\nfor w in text.split():\n    counts[w] = counts.get(w, 0) + 1\nfor w, c in sorted(counts.items(), key=lambda kv: -kv[1]):\n    print(f"{w:6s} {c}")'},
 {cat:'Python',icon:'🎲',title:{en:'Guess-my-number logic',de:'Zahlenraten-Logik',fa:'منطق حدس عدد'},
  code:'secret = 37\nlow, high, tries = 1, 100, 0\nwhile True:\n    guess = (low + high) // 2\n    tries += 1\n    print("guess:", guess)\n    if guess == secret:\n        print("found in", tries, "tries!"); break\n    if guess < secret: low = guess + 1\n    else: high = guess - 1'},
 {cat:'Python',icon:'📝',title:{en:'Prime numbers',de:'Primzahlen',fa:'اعداد اول'},
  code:'def is_prime(n):\n    if n < 2: return False\n    for d in range(2, int(n**0.5) + 1):\n        if n % d == 0: return False\n    return True\n\nprimes = [n for n in range(2, 60) if is_prime(n)]\nprint(primes)'},
 {cat:'NumPy',icon:'🎯',title:{en:'Estimate π with random points',de:'π mit Zufallspunkten schätzen',fa:'تخمین π با نقاط تصادفی'},
  code:'import numpy as np\nrng = np.random.default_rng(0)\nN = 200_000\nx, y = rng.random(N), rng.random(N)\ninside = (x**2 + y**2 <= 1).sum()\nprint("π ≈", 4 * inside / N)'},
 {cat:'NumPy',icon:'🧮',title:{en:'Matrix multiplication',de:'Matrixmultiplikation',fa:'ضرب ماتریس'},
  code:'import numpy as np\nA = np.array([[1, 2], [3, 4]])\nB = np.array([[5, 6], [7, 8]])\nprint(A @ B)          # matrix product\nprint(np.linalg.det(A))  # determinant'},
 {cat:'NumPy',icon:'🌡️',title:{en:'Normalize data (z-score)',de:'Daten normalisieren (z-Score)',fa:'نرمال‌سازی داده (z-score)'},
  code:'import numpy as np\nx = np.array([12., 15., 9., 20., 14., 11.])\nz = (x - x.mean()) / x.std()\nprint(np.round(z, 2))\nprint("mean ≈", round(z.mean(), 6), "std ≈", round(z.std(), 6))'},
 {cat:'SciPy',icon:'📐',title:{en:'Solve an equation (root finding)',de:'Gleichung lösen (Nullstelle)',fa:'حل معادله (ریشه‌یابی)'},
  code:'from scipy import optimize\nimport numpy as np\n\n# solve cos(x) = x\nroot = optimize.brentq(lambda x: np.cos(x) - x, 0, 1)\nprint("x =", round(root, 6))'},
 {cat:'SciPy',icon:'🎢',title:{en:'Curve fitting',de:'Kurvenanpassung',fa:'برازش منحنی'},
  code:'import numpy as np\nimport matplotlib.pyplot as plt\nfrom scipy.optimize import curve_fit\n\nrng = np.random.default_rng(3)\nx = np.linspace(0, 4, 40)\ny = 2.5 * np.exp(-1.3 * x) + rng.normal(scale=0.1, size=40)\n\nf = lambda x, a, b: a * np.exp(-b * x)\n(a, b), _ = curve_fit(f, x, y)\nprint(f"fit: a={a:.2f}, b={b:.2f}")\n\nplt.scatter(x, y, s=14, label="data")\nplt.plot(x, f(x, a, b), "r-", label="fit")\nplt.legend(); plt.show()'},
 {cat:'SciPy',icon:'∫',title:{en:'Numeric integration',de:'Numerische Integration',fa:'انتگرال عددی'},
  code:'from scipy import integrate\nimport numpy as np\n\nf = lambda x: np.exp(-x**2)\narea, err = integrate.quad(f, -np.inf, np.inf)\nprint("Gauss integral:", round(area, 6))\nprint("sqrt(pi)      :", round(np.sqrt(np.pi), 6))'},
 {cat:'Pandas',icon:'🏙️',title:{en:'City table: filter & sort',de:'Städtetabelle: filtern & sortieren',fa:'جدول شهرها: فیلتر و مرتب‌سازی'},
  code:'import pandas as pd\ndf = pd.DataFrame({\n    "city": ["Berlin","Munich","Hamburg","Cologne","Frankfurt"],\n    "pop":  [3.7, 1.5, 1.9, 1.1, 0.76],\n    "state":["BE","BY","HH","NW","HE"],\n})\nprint(df.sort_values("pop", ascending=False))\nprint()\nprint(df[df["pop"] > 1.2][["city","pop"]])'},
 {cat:'Pandas',icon:'🛒',title:{en:'Sales analysis with groupby',de:'Verkaufsanalyse mit groupby',fa:'تحلیل فروش با groupby'},
  code:'import pandas as pd\nsales = pd.DataFrame({\n    "month":  ["Jan","Jan","Feb","Feb","Mar","Mar"],\n    "product":["A","B","A","B","A","B"],\n    "revenue":[100, 150, 120, 130, 160, 170],\n})\nprint(sales.groupby("month")["revenue"].sum())\nprint()\nprint(sales.pivot_table(index="month", columns="product", values="revenue"))'},
 {cat:'Pandas',icon:'🧹',title:{en:'Missing values',de:'Fehlende Werte',fa:'مقادیر گمشده'},
  code:'import pandas as pd\nimport numpy as np\ndf = pd.DataFrame({"a":[1, np.nan, 3, 4], "b":[10, 20, np.nan, 40]})\nprint(df)\nprint()\nprint("nulls:\\n", df.isna().sum())\nprint()\nprint(df.fillna(df.mean()))'},
 {cat:'Pandas',icon:'📈',title:{en:'DataFrame → chart',de:'DataFrame → Diagramm',fa:'دیتافریم ← نمودار'},
  code:'import pandas as pd\nimport matplotlib.pyplot as plt\ndf = pd.DataFrame({\n    "year": [2019, 2020, 2021, 2022, 2023],\n    "users":[120, 180, 260, 410, 640],\n})\nplt.plot(df.year, df.users, "o-", color="#4b8bbe")\nplt.title("User growth")\nplt.xlabel("year"); plt.ylabel("users (k)")\nplt.grid(True); plt.show()'},
 {cat:'Matplotlib',icon:'🌀',title:{en:'Spiral (polar plot)',de:'Spirale (Polarplot)',fa:'مارپیچ (نمودار قطبی)'},
  code:'import numpy as np\nimport matplotlib.pyplot as plt\ntheta = np.linspace(0, 6*np.pi, 500)\nr = theta\nax = plt.subplot(projection="polar")\nax.plot(theta, r, color="#c0356b")\nplt.title("Archimedean spiral")\nplt.show()'},
 {cat:'Matplotlib',icon:'🚶',title:{en:'Random walk',de:'Zufallsbewegung',fa:'گام تصادفی'},
  code:'import numpy as np\nimport matplotlib.pyplot as plt\nrng = np.random.default_rng(11)\nsteps = rng.choice([-1, 1], size=1000)\nwalk = steps.cumsum()\nplt.plot(walk, lw=1)\nplt.title("1-D random walk")\nplt.show()'},
 {cat:'Matplotlib',icon:'🗺️',title:{en:'Heatmap of a function',de:'Heatmap einer Funktion',fa:'نقشه حرارتی یک تابع'},
  code:'import numpy as np\nimport matplotlib.pyplot as plt\nx = np.linspace(-3, 3, 200)\nX, Y = np.meshgrid(x, x)\nZ = np.sin(X*Y)\nplt.imshow(Z, extent=[-3,3,-3,3], cmap="magma", origin="lower")\nplt.colorbar(); plt.title("sin(x·y)")\nplt.show()'},
 {cat:'Matplotlib',icon:'🎛️',title:{en:'Subplots (2×2 dashboard)',de:'Subplots (2×2-Dashboard)',fa:'زیرنمودارها (داشبورد ۲×۲)'},
  code:'import numpy as np\nimport matplotlib.pyplot as plt\nx = np.linspace(0, 2*np.pi, 200)\nfig, ax = plt.subplots(2, 2, figsize=(8, 6))\nax[0,0].plot(x, np.sin(x));  ax[0,0].set_title("sin")\nax[0,1].plot(x, np.cos(x), "r"); ax[0,1].set_title("cos")\nax[1,0].hist(np.random.default_rng(0).normal(size=500), bins=25)\nax[1,0].set_title("normal dist")\nax[1,1].scatter(np.random.rand(80), np.random.rand(80))\nax[1,1].set_title("random scatter")\nplt.tight_layout(); plt.show()'},
 {cat:'Matplotlib',icon:'🥧',title:{en:'Pie chart',de:'Kreisdiagramm',fa:'نمودار دایره‌ای'},
  code:'import matplotlib.pyplot as plt\nsizes = [45, 25, 20, 10]\nlabels = ["Python", "C++", "Rust", "other"]\nplt.pie(sizes, labels=labels, autopct="%1.0f%%",\n        colors=["#4b8bbe","#2bb5a0","#f5b027","#c0356b"])\nplt.title("Favourite languages")\nplt.show()'},
];
